# Generated by Django 5.2.7 on 2025-10-17 12:03

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_alter_user_options_user_date_joined_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
    ]
