# Generated by Django 5.2.7 on 2025-11-06 12:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0007_alter_expense_amount_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
