# Generated by Django 5.2.7 on 2025-11-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0008_alter_budget_amount_alter_budget_current_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance_app.expensecategory'),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='finance_app.incomecategory'),
        ),
    ]
